package hack.core.models;

public enum ResearchType {
	
	UPGRADE_SPEED, UPGRADE_PARALLEL, MONEY_RESERVED, MONEY_PASSIVE, //LIMIT LEVELS
	
	RECRUITMENT_SPEED, RECRUITMENT_PARALLEL, RECRUITMENT_COST, MISSIONS_LEVEL, //LIMIT LEVELS
	
	DEFENCE_BASE, DEFENSE_HARDEN_FIREWALL, DEFENSE_HARDEN_PHYSICAL, DEFENSE_HARDEN_DATA,
	
	ATTACK_BONUS_FIREWALL, ATTACK_BONUS_PHYSICAL, ATTACK_BONUS_DATA,
	
	MONEY_ATTACK, MONEY_DEFENSE, SCAN_POWER
}
